Repository asfadmin/Discovery-WKTUtils, pull requests merged in 2021-08, with the labels that each got.

#380 Automatic merge triggered from dependabot/pip/prod/progress-1.6 to devel
  requirements.txt
Labels: auto merge, dependancies

#382 Automatic merge triggered from dependabot/pip/prod/scipy-1.7.1 to devel
  requirements.txt
Labels: auto merge, dependancies

#388 Automatic merge triggered from dependabot/pip/prod/distro-1.6.0 to devel
  requirements.txt
Labels: auto merge, dependancies

#392 v1.1.0 Release: switching to pytest-automation, test sutie refactor, issues added, requirements.txt updated
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/actions/pytest-automation/action.yml
  .github/workflows/auto-merge-nonprod.yml
  .github/workflows/auto-merge-prod.yml
  .github/workflows/changelog.yml
  README.md
  requirements.txt
  yml_tests/pytest_managers.py
  yml_tests/test_filesToWKT.py
  yml_tests/test_repairWKT.py
  yml_tests/test_validateWKT.py
Labels: minor

#385 Automatic merge triggered from dependabot/pip/prod/progress-1.6 to test
  requirements.txt
Labels: auto merge, dependancies

#386 Automatic merge triggered from dependabot/pip/prod/scipy-1.7.1 to test
  requirements.txt
Labels: auto merge, dependancies

#389 Automatic merge triggered from dependabot/pip/prod/distro-1.6.0 to test
  requirements.txt
Labels: auto merge, dependancies

#393 Updated changelog and requirements.txt, test suite refactor
  CHANGELOG.md
  requirements.txt
  yml_tests/pytest_managers.py
  yml_tests/test_filesToWKT.py
  yml_tests/test_repairWKT.py
Labels: skip-release

#396 Bumping up pip versions dependabot flagged
  requirements.txt
Labels: skip-release
