Repository asfadmin/Discovery-WKTUtils, pull requests merged in 2021-05, with the labels that each got.

#196 Adding extra labels to 'wait' action
  .github/workflows/auto-merge-nonprod.yml
  .github/workflows/auto-merge-prod.yml
Labels: auto merge

#197 Adding extra labels to 'wait' action, to see if it's waiting for the wrong label
  .github/workflows/auto-merge-nonprod.yml
  .github/workflows/auto-merge-prod.yml
Labels: skip-release

#200 Automatic merge triggered from cameron to devel
  README.md
Labels: auto merge, dependancies

#199 Removed newline, to test automerge actions to prod
  README.md
Labels: auto merge, skip-release

#201 Automatic merge triggered from cameron to test
  README.md
Labels: auto merge, dependancies

#208 Automatic merge triggered from cameron to devel
  README.md
Labels: auto merge, dependancies

#209 Automatic merge triggered from cameron to test
  README.md
Labels: auto merge, dependancies

#211 Automatic merge triggered from dependabot/pip/prod/six-1.16.0 to devel
  requirements.txt
Labels: auto merge, dependancies

#213 Adding "on: branches: prod" for security updates
  .github/workflows/auto-merge-prod.yml
  README.md
  requirements.txt
Labels: skip-release

#207 Adding new line, to trigger automatic merge to prod agian
  README.md
Labels: auto merge, skip-release

#216 Automatic merge triggered from cameron to devel
  README.md
Labels: auto merge, dependancies

#217 Automatic merge triggered from cameron to test
  README.md
Labels: auto merge, dependancies

#218 Automatic merge triggered from cameron to test
  .github/workflows/auto-merge-nonprod.yml
  .github/workflows/auto-merge-prod.yml
Labels: auto merge, dependancies

#219 Automatic merge triggered from cameron to devel
  .github/workflows/auto-merge-prod.yml
Labels: auto merge, dependancies

#220 Automatic merge triggered from cameron to test
  .github/workflows/auto-merge-prod.yml
Labels: auto merge, dependancies

#221 Automatic merge triggered from cameron to devel
  .github/workflows/auto-merge-prod.yml
Labels: auto merge, dependancies

#222 Automatic merge triggered from cameron to test
  .github/workflows/auto-merge-prod.yml
Labels: auto merge, dependancies

#223 Automatic merge triggered from cameron to devel
  .github/workflows/auto-merge-prod.yml
Labels: auto merge, dependancies

#224 Automatic merge triggered from cameron to test
  .github/workflows/auto-merge-prod.yml
Labels: auto merge, dependancies

#225 Automatic merge triggered from cameron to devel
  .github/workflows/auto-merge-prod.yml
Labels: auto merge, dependancies

#226 Automatic merge triggered from cameron to test
  .github/workflows/auto-merge-prod.yml
Labels: auto merge, dependancies

#227 Automatic merge triggered from cameron to devel
  .github/workflows/auto-merge-prod.yml
Labels: auto merge, dependancies

#228 Automatic merge triggered from cameron to test
  .github/workflows/auto-merge-prod.yml
Labels: auto merge, dependancies

#215 Removing new line, to trigger automatic pr
  .github/workflows/auto-merge-nonprod.yml
  .github/workflows/auto-merge-prod.yml
  README.md
Labels: skip-release

#230 Automatic merge triggered from cameron to devel
  .github/workflows/auto-merge-prod.yml
  .github/workflows/prod-request-merged.yml
Labels: auto merge, dependancies

#231 Automatic merge triggered from cameron to test
  .github/workflows/auto-merge-prod.yml
  .github/workflows/prod-request-merged.yml
Labels: auto merge, dependancies

#229 Cleanup auto-merge action suites
  .github/workflows/auto-merge-prod.yml
  .github/workflows/prod-request-merged.yml
Labels: skip-release

#236 Action refactoring / bug fix, bump up attrs version to latest
  .github/workflows/auto-merge-nonprod.yml
  .github/workflows/prod-request-merged.yml
  requirements.txt
Labels: skip-release

#239 Automatic merge triggered from cameron to devel
  README.md
Labels: auto merge, dependancies

#238 Automatic merge triggered from cameron to devel
  README.md
Labels: auto merge, dependancies

#241 Automatic merge triggered from cameron to test
  README.md
Labels: auto merge, dependancies

#237 Removing newline to trigger automatic pipeline
  README.md
Labels: skip-release
