Repository asfadmin/Discovery-WKTUtils, pull requests merged in 2021-06, with the labels that each got.

#249 Pip package updates
  requirements.txt
Labels: skip-release

#252 Updating two packages to latest and greatest
  requirements.txt
Labels: skip-release

#261 Test
  .github/dependabot.yml
  requirements.txt
Labels: skip-release

#264 Added env: GITHUB_TOKEN with the other token keyword still there
  .github/workflows/auto-merge-prod.yml
Labels: skip-release

#267 Switching to pull_request_target to let Dependabot open PR's w/ label
  .github/workflows/auto-merge-prod.yml
  requirements.txt
Labels: skip-release

#269 Automatic merge triggered from dependabot/pip/prod/dependancy-bumper-0.0.3 to devel
  requirements.txt
Labels: auto merge, dependancies

#270 Automatic merge triggered from dependabot/pip/prod/dependancy-bumper-0.0.3 to test
  requirements.txt
Labels: auto merge, dependancies

#272 Automatic merge triggered from dependabot/pip/prod/dependancy-bumper-0.0.4 to devel
  requirements.txt
Labels: auto merge, dependancies

#273 Automatic merge triggered from dependabot/pip/prod/dependancy-bumper-0.0.4 to test
  requirements.txt
Labels: auto merge, dependancies

#275 Test
  .github/workflows/auto-merge-nonprod.yml
  .github/workflows/auto-merge-prod.yml
  .github/workflows/changelog.yml
  .github/workflows/label-prod-pr.yml
  .github/workflows/prod-request-merged.yml
  .github/workflows/pypi-publish.yml
  .github/workflows/run-pytest.yml
Labels: skip-release

#278 Automatic merge triggered from cameron to devel
  README.md
Labels: auto merge, dependancies

#279 Automatic merge triggered from cameron to test
  README.md
Labels: auto merge, dependancies

#277 Adding newline at end of readme, to test 'auto merge' label
  README.md
Labels: skip-release

#281 Automatic merge triggered from cameron to devel
  .github/workflows/auto-merge-prod.yml
Labels: auto merge, dependancies

#282 Automatic merge triggered from cameron to test
  .github/workflows/auto-merge-prod.yml
Labels: auto merge, dependancies

#280 Adding sleep before checking for actions, to make sure they have time…
  .github/workflows/auto-merge-prod.yml
Labels: skip-release

#284 Automatic merge triggered from cameron to devel
  README.md
Labels: auto merge, dependancies

#285 Automatic merge triggered from cameron to test
  README.md
Labels: auto merge, dependancies

#283 Removing new line, to test auto merge label
  README.md
Labels: skip-release

#289 Automatic merge triggered from dependabot/pip/prod/scipy-1.7.0 to devel
  requirements.txt
Labels: auto merge, dependancies

#293 Fixing typo in changelog action
  .github/workflows/auto-merge-prod.yml
  .github/workflows/changelog.yml
  README.md
Labels: skip-release

#295 Automatic merge triggered from cameron to devel
  README.md
Labels: auto merge, dependancies

#296 Automatic merge triggered from cameron to test
  README.md
Labels: auto merge, dependancies

#294 Removing newline, to trigger automerge pipeline testing
  README.md
Labels: skip-release

#299 Fixing typo in merge-after action
  .github/workflows/auto-merge-prod.yml
  .github/workflows/prod-request-merged.yml
Labels: auto merge, skip-release

#308 Adding newline, to trigger auto update pipeline
  README.md
Labels: auto merge, skip-release

#314 Apperently you can't have an ID, that even contains another ID
  .github/workflows/auto-merge-prod.yml
Labels: skip-release

#316 Automatic merge triggered from cameron to devel
  README.md
Labels: auto merge, dependancies

#317 Automatic merge triggered from cameron to test
  README.md
Labels: auto merge, dependancies

#320 Automatic merge triggered from dependabot/pip/prod/pandas-1.2.5 to devel
  requirements.txt
Labels: auto merge, dependancies

#321 Automatic merge triggered from dependabot/pip/prod/numpy-1.21.0 to devel
  requirements.txt
Labels: auto merge, dependancies

#326 Automatic merge triggered from dependabot/pip/prod/contextlib2-21.6.0 to devel
  requirements.txt
Labels: auto merge, dependancies

#327 Automatic merge triggered from dependabot/pip/prod/urllib3-1.26.6 to devel
  requirements.txt
Labels: auto merge, dependancies
